"""add yunxiao host and inventory tables

Revision ID: 172c4918f1b4
Revises: 0002_default_timestamps
Create Date: 2026-06-18 16:54:05.842902

"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '172c4918f1b4'
down_revision: str | None = '0002_default_timestamps'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述/关键词'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='英文名（OA账号名）'),
    sa.Column('display_name', sa.String(length=64), nullable=True, comment='中文名/昵称'),
    sa.Column('team', sa.String(length=128), nullable=True, comment='所属团队'),
    sa.Column('role', sa.String(length=128), nullable=True, comment='角色/职责简述'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active/vacation/left'),
    sa.Column('wecom_id', sa.String(length=64), nullable=True, comment='企微ID'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='手机号'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=512), nullable=False, comment='问题'),
    sa.Column('answer', sa.Text(), nullable=False, comment='回答（支持HTML）'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='FAQ分类'),
    sa.Column('tags', sa.String(length=256), nullable=True, comment='标签'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False, comment='标题'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='分类：manual/sop/faq/link'),
    sa.Column('content', sa.Text(), nullable=True, comment='正文内容（Markdown）'),
    sa.Column('summary', sa.String(length=512), nullable=True, comment='摘要'),
    sa.Column('tags', sa.String(length=512), nullable=True, comment='标签，逗号分隔'),
    sa.Column('source_file', sa.String(length=256), nullable=True, comment='来源文件路径'),
    sa.Column('url', sa.String(length=512), nullable=True, comment='外部链接URL'),
    sa.Column('importance', sa.Integer(), nullable=False, comment='重要度 1-5'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active/archived'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_articles'))
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False, comment='push_doc / add_rows / switch_sheet'),
    sa.Column('target', sa.String(length=128), nullable=False, comment='操作目标：sheet_name:row'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='ok / warn / fail'),
    sa.Column('message', sa.Text(), nullable=True, comment='结果消息'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='详细信息（mismatches等）'),
    sa.Column('workorder_no', sa.String(length=32), nullable=True, comment='关联工单号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_table('platform_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='平台名称'),
    sa.Column('purpose', sa.String(length=512), nullable=True, comment='用途描述'),
    sa.Column('url', sa.String(length=512), nullable=False, comment='链接地址'),
    sa.Column('importance', sa.Integer(), nullable=False, comment='重要度 1-5'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='分类'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_links'))
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='工单编号 WO-YYYYMMDD-XXXX'),
    sa.Column('order_type', sa.String(length=32), nullable=False, comment='ecm_export / host_deploy / migration / repair'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='工单标题'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='submitted/pending/processing/verifying/completed/rejected'),
    sa.Column('creator', sa.String(length=64), nullable=False, comment='提交人（OA英文名）'),
    sa.Column('assignee', sa.String(length=64), nullable=True, comment='当前处理人'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='工单详情（结构化字段）'),
    sa.Column('pre_checks', sa.JSON(), nullable=True, comment='前置校验结果'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1=紧急 2=普通 3=低'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('order_no', name=op.f('uq_work_orders_order_no'))
    )
    op.create_table('zone_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('machine_type', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('is_tez', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_devices'))
    )
    op.create_index(op.f('ix_zone_devices_asset_id'), 'zone_devices', ['asset_id'], unique=False)
    op.create_index(op.f('ix_zone_devices_zone'), 'zone_devices', ['zone'], unique=False)
    op.create_table('zone_snapshots',
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('idc', sa.String(length=128), nullable=True),
    sa.Column('total_positions', sa.Integer(), nullable=False),
    sa.Column('free_count', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('other_count', sa.Integer(), nullable=False),
    sa.Column('total_assets', sa.Integer(), nullable=False),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.Column('offline_count', sa.Integer(), nullable=False),
    sa.Column('non_tez_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('zone', name=op.f('pk_zone_snapshots'))
    )
    op.create_table('escalation_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False, comment='升级层级 1/2/3'),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='该层级说明'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_escalation_paths_category_id_categories')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_escalation_paths_contact_id_contacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_paths'))
    )
    op.create_table('responsibilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False, comment='1=主负责人, 2=备份, 3=上升'),
    sa.Column('note', sa.Text(), nullable=True, comment='备注'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_responsibilities_category_id_categories')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_responsibilities_contact_id_contacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsibilities'))
    )
    op.create_table('work_order_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False, comment='create/assign/process/verify/complete/reject/comment'),
    sa.Column('operator', sa.String(length=64), nullable=False, comment='操作人'),
    sa.Column('content', sa.Text(), nullable=True, comment='操作内容/备注'),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['work_orders.id'], name=op.f('fk_work_order_logs_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order_logs')
    op.drop_table('responsibilities')
    op.drop_table('escalation_paths')
    op.drop_table('zone_snapshots')
    op.drop_index(op.f('ix_zone_devices_zone'), table_name='zone_devices')
    op.drop_index(op.f('ix_zone_devices_asset_id'), table_name='zone_devices')
    op.drop_table('zone_devices')
    op.drop_table('work_orders')
    op.drop_table('platform_links')
    op.drop_table('operation_logs')
    op.drop_table('knowledge_articles')
    op.drop_table('faqs')
    op.drop_table('contacts')
    op.drop_table('categories')
    # ### end Alembic commands ###
