#!/usr/bin/env bash
# scripts/install-hooks.sh
# 安装 git hooks（pre-commit 敏感数据扫描）
# 用法：./scripts/install-hooks.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOKS_DIR="$ROOT/.git/hooks"
SOURCE="$ROOT/scripts/pre-commit-check.sh"

if [[ ! -d "$ROOT/.git" ]]; then
    echo "❌ 当前目录不是 git 仓库根"
    exit 1
fi

if [[ ! -f "$SOURCE" ]]; then
    echo "❌ 未找到 $SOURCE"
    exit 1
fi

# 安装 pre-commit
TARGET="$HOOKS_DIR/pre-commit"

if [[ -f "$TARGET" ]]; then
    if grep -q "pre-commit-check.sh" "$TARGET" 2>/dev/null; then
        echo "ℹ️  pre-commit 钩子已安装，跳过"
        exit 0
    fi
    echo "⚠️  $TARGET 已存在但不是本项目的钩子，备份为 ${TARGET}.bak"
    mv "$TARGET" "${TARGET}.bak"
fi

cat > "$TARGET" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
exec "$(git rev-parse --show-toplevel)/scripts/pre-commit-check.sh"
HOOK

chmod +x "$TARGET"
chmod +x "$SOURCE"

echo "✅ pre-commit 钩子安装成功"
echo "   位置: $TARGET"
echo "   实现: $SOURCE"
echo ""
echo "📖 测试一下:"
echo "   echo 'TYSV20060001A test' > /tmp/test.txt"
echo "   git add /tmp/test.txt  # 这只是演示,别真的 add"
echo "   git commit -m 'test'   # 应该被拒绝"
